### ISSUE TITLE
pluginDB Update errno2

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#13]
Ich hab xStream neuinstalliert ohne irgendwelche Einstellungen, dann beendet und neugestartet. Das Problem: Es wird nicht angezeigt, dass keine Site-Plugins aktiviert sind und ohne natürlich nichts geht.

TODO: Dialog einbauen für den Benutzer und anschließend Settings öffnen.

> Traceback (most recent call last):
>   File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.xstream\default.py", line 32, in <module>
>     run()
>   File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.xstream\xstream.py", line 17, in run
>     parseUrl()
>   File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.xstream\xstream.py", line 204, in parseUrl
>     showMainMenu(sFunction)
>   File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.xstream\xstream.py", line 209, in showMainMenu
>     aPlugins = oPluginHandler.getAvailablePlugins()
>   File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.xstream\resources\lib\handler\pluginHandler.py", line 50, in getAvailablePlugins
>     self.__updatePluginDB(pluginDB)
>   File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.xstream\resources\lib\handler\pluginHandler.py", line 72, in __updatePluginDB
>     file = open(self.pluginDBFile, 'w')
> IOError: [Errno 2] No such file or directory: u'C:\Users\admin\AppDat...

**Comment by sraedler** [comment]
Es wird nun eine Meldung angezeigt, siehe 7152d42
